## 1.传统处理异常

我们在单线程中处理异常往往是向上抛, 或者通过try…catch的方式处理, 而在多线程环境中,子线程抛出的异常主线程往往无法处理

### 1-1.子线程向上抛异常

通过如下的代码验证, 我们知道子线程抛出异常, 父线程没有中断, 并继续完成自己的任务

```java
public class ThreadException implements Runnable{

    @Override
    public void run() {
        throw new RuntimeException("Run err...");
    }

    public static void main(String[] args) {
        new Thread(new ThreadException()).start();

        for (int i = 0; i < 10; i++) {
            System.out.println(i);
        }
    }
}

// 运行结果
Exception in thread "Thread-0" java.lang.RuntimeException: Run err...
0
	at com.polar.concurrence.thread.ThreadException.run(ThreadException.java:10)
1
	at java.lang.Thread.run(Thread.java:748)
2
3
4
5
6
7
8
9
```

### 1-2.try…catch捕获异常

通过下面的代码实验, 我们发现try...catch并不能捕获子线程的异常

```java
public class ThreadException implements Runnable{

    @Override
    public void run() {
        throw new RuntimeException("Run err...");
    }

    public static void main(String[] args) {
        try {
            new Thread(new ThreadException()).start();
            Thread.sleep(1000);

            new Thread(new ThreadException()).start();
            Thread.sleep(1000);

            new Thread(new ThreadException()).start();
            Thread.sleep(1000);
        } catch (Exception e) {
            System.out.println("err catch...");
        }
    }
}

// 运行结果
Exception in thread "Thread-0" java.lang.RuntimeException: Run err...
	at com.polar.concurrence.thread.ThreadException.run(ThreadException.java:10)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "Thread-1" java.lang.RuntimeException: Run err...
	at com.polar.concurrence.thread.ThreadException.run(ThreadException.java:10)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "Thread-2" java.lang.RuntimeException: Run err...
	at com.polar.concurrence.thread.ThreadException.run(ThreadException.java:10)
	at java.lang.Thread.run(Thread.java:748)
```

## 2.多线程异常处理的两种策略

### 2-1.手动在子线程中try-catch(不推荐)

```java
public class ThreadException implements Runnable{

    @Override
    public void run() {
        try {
            throw new RuntimeException("Run err...");
        } catch (Exception e) {
            System.out.println("Thread err warning....");
        }
    }

    public static void main(String[] args) throws InterruptedException {
        new Thread(new ThreadException()).start();
        Thread.sleep(1000);

        new Thread(new ThreadException()).start();
        Thread.sleep(1000);
    }
}

// 运行结果
Thread err warning....
Thread err warning....
```

### 2-2.Thread类中提供的UncaughtExceptionHandler异常处理

这个异常处理器的设计可以针对不同维度设计

- 给程序统一设计一个异常处理器
- 每个线程单独设计
- 给线程池设计一个

```java
// 定义一个异常处理器
public class MyUncaughtExceptionHandler implements Thread.UncaughtExceptionHandler {

    private String handlerName;

    public MyUncaughtExceptionHandler(String handlerName) {
        this.handlerName = handlerName;
    }

    @Override
    public void uncaughtException(Thread t, Throwable e) {
        System.out.println("捕获到了异常, 处理器:" + this.handlerName);
        System.out.println("异常信息: threadName:" + t.getName() + "  e:" + e);
    }
}


// 使用异常处理器
public class ThreadException implements Runnable{

    @Override
    public void run() {
        throw new RuntimeException("Run err...");
    }

    public static void main(String[] args) throws InterruptedException {
        Thread.setDefaultUncaughtExceptionHandler(new MyUncaughtExceptionHandler("异常处理器A"));
        new Thread(new ThreadException()).start();
    }
}

// 运行结果
捕获到了异常, 处理器:异常处理器A
异常信息: threadName:Thread-0  e:java.lang.RuntimeException: Run err...
```

